[theme]
# Primary accent color for interactive elements.
primaryColor = "#E6A69C"

# Background color for the main content area.
backgroundColor = "#FFFFFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#F7F5F3"

# Color used for almost all text.
textColor = "#0B3850"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
